package model.beans;
// Generated 06/10/2015 13:16:55 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Collection;
import java.util.Objects;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Alarme generated by hbm2java
 */
@Entity
public class Alarme  implements Serializable {
    
    @Id
    private String codigoAlarme;
    private String descricaoAlarme;
    @OneToMany
    private Collection<Evento> eventos;

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + Objects.hashCode(this.codigoAlarme);
        hash = 67 * hash + Objects.hashCode(this.descricaoAlarme);
        hash = 67 * hash + Objects.hashCode(this.eventos);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Alarme other = (Alarme) obj;
        if (!Objects.equals(this.codigoAlarme, other.codigoAlarme)) {
            return false;
        }
        if (!Objects.equals(this.descricaoAlarme, other.descricaoAlarme)) {
            return false;
        }
        if (!Objects.equals(this.eventos, other.eventos)) {
            return false;
        }
        return true;
    }
    
    public String getCodigoAlarme() {
        return codigoAlarme;
    }

    public void setCodigoAlarme(String codigoAlarme) {
        this.codigoAlarme = codigoAlarme;
    }

    public String getDescricaoAlarme() {
        return descricaoAlarme;
    }

    public void setDescricaoAlarme(String descricaoAlarme) {
        this.descricaoAlarme = descricaoAlarme;
    }

    public Collection<Evento> getEventos() {
        return eventos;
    }

    public void setEventos(Collection<Evento> eventos) {
        this.eventos = eventos;
    }       
}


