package model.beans;
// Generated 06/10/2015 13:16:55 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Collection;
import java.util.Objects;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Equipamento generated by hbm2java
 */
@Entity
public class Equipamento  implements Serializable {
    
    @Id
    private String codigoEquipamento;
    private Short estado;
    @OneToMany
    private Collection<Evento> eventos;
    @OneToMany
    private Collection<Operacao> operacoes;

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 89 * hash + Objects.hashCode(this.codigoEquipamento);
        hash = 89 * hash + Objects.hashCode(this.estado);
        hash = 89 * hash + Objects.hashCode(this.operacoes);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Equipamento other = (Equipamento) obj;
        if (!Objects.equals(this.codigoEquipamento, other.codigoEquipamento)) {
            return false;
        }
        if (!Objects.equals(this.estado, other.estado)) {
            return false;
        }
        if (!Objects.equals(this.eventos, other.eventos)) {
            return false;
        }
        if (!Objects.equals(this.operacoes, other.operacoes)) {
            return false;
        }
        return true;
    }
    
    public String getCodigoEquipamento() {
        return codigoEquipamento;
    }

    public void setCodigoEquipamento(String codigoEquipamento) {
        this.codigoEquipamento = codigoEquipamento;
    }

    public Short getEstado() {
        return estado;
    }

    public void setEstado(Short estado) {
        this.estado = estado;
    }

    public Collection<Evento> getEventos() {
        return eventos;
    }

    public void setEventos(Collection<Evento> eventos) {
        this.eventos = eventos;
    }

    public Collection<Operacao> getOperacoes() {
        return operacoes;
    }

    public void setOperacoes(Collection<Operacao> operacoes) {
        this.operacoes = operacoes;
    }   
}


