package model.beans;
// Generated 06/10/2015 13:16:55 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evento generated by hbm2java
 */
@Entity
public class Evento  implements Serializable {

    @EmbeddedId
    private EventoId id;
    @Temporal(TemporalType.DATE)
    private Date diaEvento;
    @Temporal(TemporalType.DATE)
    private Date horaEvento;

    public EventoId getId() {
        return id;
    }

    public void setId(EventoId id) {
        this.id = id;
    }

    public Date getDiaEvento() {
        return diaEvento;
    }

    public void setDiaEvento(Date diaEvento) {
        this.diaEvento = diaEvento;
    }

    public Date getHoraEvento() {
        return horaEvento;
    }

    public void setHoraEvento(Date horaEvento) {
        this.horaEvento = horaEvento;
    }
}


