package model.beans;
// Generated 06/10/2015 13:16:55 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import java.util.Objects;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Morador generated by hbm2java
 */
@Entity
public class Morador  implements Serializable {
    
    @Id
    private String login;
    private String nome;
    @Temporal(TemporalType.DATE)
    private Date dataNascimento;
    private String senha;
    @OneToMany
    private Collection<Operacao> operacaoes;

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 11 * hash + Objects.hashCode(this.getLogin());
        hash = 11 * hash + Objects.hashCode(this.getNome());
        hash = 11 * hash + Objects.hashCode(this.getDataNascimento());
        hash = 11 * hash + Objects.hashCode(this.getSenha());
        hash = 11 * hash + Objects.hashCode(this.getOperacaoes());
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Morador other = (Morador) obj;
        if (!Objects.equals(this.login, other.login)) {
            return false;
        }
        if (!Objects.equals(this.nome, other.nome)) {
            return false;
        }
        if (!Objects.equals(this.dataNascimento, other.dataNascimento)) {
            return false;
        }
        if (!Objects.equals(this.senha, other.senha)) {
            return false;
        }
        if (!Objects.equals(this.operacaoes, other.operacaoes)) {
            return false;
        }
        return true;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Date getDataNascimento() {
        return dataNascimento;
    }

    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public Collection<Operacao> getOperacaoes() {
        return operacaoes;
    }

    public void setOperacaoes(Collection<Operacao> operacaoes) {
        this.operacaoes = operacaoes;
    }
}


