package model.beans;
// Generated 06/10/2015 13:16:55 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Operacao generated by hbm2java
 */
@Entity
public class Operacao  implements java.io.Serializable {
    
    @EmbeddedId
    private OperacaoId id;
    @Temporal(TemporalType.DATE)
    private Date diaOperacao;
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date horaOpercao;

    public OperacaoId getId() {
        return id;
    }

    public void setId(OperacaoId id) {
        this.id = id;
    }

    public Date getDiaOperacao() {
        return diaOperacao;
    }

    public void setDiaOperacao(Date diaOperacao) {
        this.diaOperacao = diaOperacao;
    }

    public Date getHoraOpercao() {
        return horaOpercao;
    }

    public void setHoraOpercao(Date horaOpercao) {
        this.horaOpercao = horaOpercao;
    }    
}


