package model.beans;
// Generated 06/10/2015 13:16:55 by Hibernate Tools 4.3.1

import java.util.Objects;
import javax.persistence.Embeddable;
import javax.persistence.ManyToOne;




/**
 * OperacaoId generated by hbm2java
 */
@Embeddable
public class OperacaoId  implements java.io.Serializable {

    @ManyToOne
    private Equipamento equipamento;
    @ManyToOne
    private Morador morador;

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 71 * hash + Objects.hashCode(this.getEquipamento());
        hash = 71 * hash + Objects.hashCode(this.getMorador());
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final OperacaoId other = (OperacaoId) obj;
        if (!Objects.equals(this.equipamento, other.equipamento)) {
            return false;
        }
        if (!Objects.equals(this.morador, other.morador)) {
            return false;
        }
        return true;
    }

    public Equipamento getEquipamento() {
        return equipamento;
    }

    public void setEquipamento(Equipamento equipamento) {
        this.equipamento = equipamento;
    }

    public Morador getMorador() {
        return morador;
    }

    public void setMorador(Morador morador) {
        this.morador = morador;
    }
}


